server:
  port: 9081
  servlet:
    context-path: /shop
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always

spring:
  application:
    name: jewelry-main-service
  datasource:
    username: ${USERNAME:jewelry_user}
    password: ${PASSWORD:jewelry_pass}
    url: jdbc:mysql:///${DB_NAME:jewelry}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  flyway:
    #change it according your local conf. @Belyakov @Gudkov
    url: jdbc:mysql://localhost:3306/${DB_NAME:jewelry}
    schemas: ${DB_NAME:jewelry}
    user: ${USERNAME:jewelry_user}
    password: ${PASSWORD:jewelry_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    locations: filesystem:src/main/resources/db.migration
    clean-disabled: false
    clean-on-validation-error: true